### ISSUE TITLE
0.0.1 crashes when trying to [i]pairs a js array

### ISSUE THREAD

**Issue by jaredallard** [daurnimator/lua.vm.js#51] opened 2016-04-12 10:34 UTC
Hi. Pretty simple reproduction. Using `0.0.1` via npm, will try master soon.

**nodejs** *only*

```js
var array = [ 'item', 'item2', 'item3'];
```

```lua
local arr = myFuncToGetJSArray();
for i, v in ipairs(arr) do
   print(v)
end
```

Pure Lua:
```lua
local tble      = {}
tble[1]         = 'item';
tble[2]         = 'item2';
local arr = js.global:Array(table.unpack(tble))
for i, v in ipairs(arr) do
   print(v)
end
```

EDIT: self built from `master` fails as well.

**Comment by jaredallard** [comment] 2016-04-12 10:58
#31 is why this doesn't work. Inject the line below `this.gc` at commit fa9d5921c60e9c640988f17f34841269f89ea16d and this is fixed.

**Comment by daurnimator** [comment] 2016-04-12 12:29
Huh? So is it fixed in master or not?

Your sample works in the repl at https://kripken.github.io/lua.vm.js/repl.html for me.

**Comment by jaredallard** [comment] 2016-04-12 19:19
@daurnimator Sorry for being confusing, this is in a node.js env.

**Comment by daurnimator** [comment] 2016-04-13 01:38
> @daurnimator Sorry for being confusing, this is in a node.js env.

Works for me:
```
$ node 
> require("./dist/lua.vm.js").L.execute('for i,v in ipairs(js.global:Array(table.unpack({"item", "item2"}))) do print(v) end')
item
item2
[]
>
```

**Comment by daurnimator** [comment] 2016-05-17 15:28
@jaredallard did you figure this out?

**Comment by jaredallard** [comment] 2016-08-04 01:32
@daurnimator Hey, for me this didn't work. The only way I got it to work was doing the aforementioned fix beforehand. Though I haven't used this in a awhile, so it is possible something may have been changed to fix it.

**Comment by daurnimator** [comment] 2016-08-16 06:51
Closing as it works for me. Will reopen if you can reproduce.

**Closed by daurnimator** 2016-08-16 06:51 UTC
